### ISSUE TITLE
Rotation Speed value invalid

### ISSUE THREAD

**Issue by mikeb1rd** [sjlu/homebridge-mila#1]
Hiya, thanks for creating the plugin. I get lots of these warnings in the logs. The Mila is in automatic mode.
```[08/07/2023, 18:09:21] [homebridge-mila] This plugin generated a warning from the characteristic 'Rotation Speed': characteristic was supplied illegal value: number -30 exceeded minimum of 0. See https://homebridge.io/w/JtMGR for more info.```

**Comment by sjlu** [comment]
Ah interesting. I may have to write some debugging code to see where Mila’s actual rotation speed matches with %.

I’ll keep this open and work on this when I have the time!

**Comment by sjlu** [comment]
@mikeb1rd released 1.2.2 to add some debugging information. If you see `Fan speed is ${device.fanSpeed}% at RPM ${device.sensors.FanSpeed}` let me know those two values.

**Comment by mikeb1rd** [comment]
`[homebridge-mila] Fan speed is -30% at RPM 0`

**Comment by sjlu** [comment]
🤦 

Fixed in 1.2.3
